### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by Madeforsweden** [kuplion/Exile-Status-Bar#1]
I need a guide to install.. :s

**Comment by northrivergeek** [comment]
Its all right there .. look at the files..  content of custom, goes in custom, override .. you just need to make a override in customcode place that in folder called overrides, or place in custom and point that to it
Edit your description.ext and initplayer as shown in those two examples

**Comment by Madeforsweden** [comment]
I actually dont have a file called custom or a file called override. but ill just try and see how it goes..
