### ISSUE TITLE
I saw you updated one file and now there is this error and no statusbar visible :)

### ISSUE THREAD

**Issue by ELRabito** [kuplion/Exile-Status-Bar#5]
Error in expression <et / 1000) toFixed 1)];
};

if (_wallet > 999999) then
{
_wallet = format ["%1M">
 0:00:11   Error position: <> 999999) then
{
_wallet = format ["%1M">
 0:00:11   Error >: Type String, expected Number,Not a Number
 0:00:11 File mpmissions\__CUR_MP.Chernarus_2035\Custom\StatusBar\statusBar_update.sqf, line 67

**Comment by kuplion** [comment]
Unfortunately I accepted a pull request that had an error in it. I will need to fix it but in the mean time you can download a commit from before the pull request was made.

**Comment by ELRabito** [comment]
I had the old files, i just wanted to inform you 👍
